### ISSUE TITLE
chart.filter() on empty chart causes SegmentationFault

### ISSUE THREAD

**Issue by kilian-gebhardt** [andreasvc/disco-dop#51]
If parsing failed because a word is not in the lexicon, then calling `filter` (on the empty chart) causes a segfault. (Note that other charts where parsing failed at a later stage can be filtered, that is, successful parsing does not seem to be a semantic prerequisite for filtering.)

MWE:
```
from discodop.containers import Grammar
from discodop.plcfrs import parse
g = Grammar([((('S', 'A'), ((0,),)), 1.0), ((('A', 'Epsilon'), ('a',)), 1.0)], start='S')
chart, msg = parse(["b"], g)
chart.filter()
```

The segfault occurs in `_filtersubtree(self, self.root(), itemstokeep)`, where `chart.parseforest[item]` is accessed. However, `chart.parseforest` is an empty vector.

**Comment by andreasvc** [comment]
Thx!

This bug report is so thorough that it must have taken longer to write than the patch ;)

BTW I'd love to hear how you're using my parser.

**Comment by kilian-gebhardt** [comment]
What took longest was identifying the problem ;-). I was not sure, if you preferred the check in `filter` or `_filtersubtree` and decided to just give a description.
