### ISSUE TITLE
discodop/_containers.h:11:10: fatal error: ../sparsepp/sparsepp/spp.h: No such file or directory

### ISSUE THREAD

**Issue by sarves** [andreasvc/disco-dop#59]
Hi,

I tried to install disco-dop on Ubuntu17 and I got the following error always though all the requirements are satisfied:

python3 setup.py install --user
running install
running bdist_egg
running egg_info
writing disco_dop.egg-info/PKG-INFO
writing dependency_links to disco_dop.egg-info/dependency_links.txt
writing entry points to disco_dop.egg-info/entry_points.txt
writing requirements to disco_dop.egg-info/requires.txt
writing top-level names to disco_dop.egg-info/top_level.txt
reading manifest file 'disco_dop.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.c' under directory 'discodop'
warning: no previously-included files matching '*.pyx' found under directory 'discodop'
warning: no previously-included files matching '*.pxi' found under directory 'discodop'
warning: no previously-included files matching '*.pxd' found under directory 'discodop'
warning: no previously-included files matching '*' found under directory 'web/grammars'
writing manifest file 'disco_dop.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'discodop._fragments' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Idiscodop -I./discodop -I/usr/include/python3.6m -c discodop/_fragments.cpp -o build/temp.linux-x86_64-3.6/discodop/_fragments.o -Isparsepp/ -Wno-strict-prototypes -Wno-unused-function -Wno-unreachable-code -Wno-sign-compare -D__STDC_LIMIT_MACROS -O3 -march=native -DNDEBUG
cc1plus: warning: command line option ‘-Wno-strict-prototypes’ is valid for C/ObjC but not for C++
In file included from discodop/_fragments.cpp:630:0:
discodop/_containers.h:11:10: fatal error: ../sparsepp/sparsepp/spp.h: No such file or directory
 #include "../sparsepp/sparsepp/spp.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:16: recipe for target 'discodop' failed
make: *** [discodop] Error 1

I tried with root privilege and as an ordinary user. 

Your input would be appreciated.

**Comment by andreasvc** [comment]
sparsepp is a submodule in this repository; you need to pass --recursive to clone to get the submodules as well:

$ git clone --recursive git://github.com/andreasvc/disco-dop.git

See also https://git-scm.com/book/en/v2/Git-Tools-Submodules

Let me know if this helps.

**Comment by sarves** [comment]
Hi
Thank you for the prompt response, yes it worked. But, got several warnings (like cc1plus: warning: command line option ‘-Wno-strict-prototypes’ is valid for C/ObjC but not for C++). Hope its OK.

**Comment by andreasvc** [comment]
Yep, those are expected. Python adds that option even though it's not applicable to C++.
